# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2wnCf5-ad-4IxQXDsYESgzUCNQbSc_G
"""

# -*- coding: utf-8 -*-
"""train.py — Script para registrar experimento MLflow"""

import os
import mlflow
import mlflow.sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.datasets import load_diabetes

# Ruta donde MLflow guardará los experimentos (en tu Drive)
os.environ["MLFLOW_TRACKING_URI"] = "file:///content/drive/MyDrive/mlruns"

# Inicia un experimento en MLflow
mlflow.set_experiment("demo-linear-regression")

with mlflow.start_run():
    # Carga datos
    data = load_diabetes()
    X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2)

    # Modelo
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    # Métricas
    mse = mean_squared_error(y_test, predictions)

    # Registro en MLflow
    mlflow.log_param("model_type", "LinearRegression")
    mlflow.log_metric("mse", mse)
    mlflow.sklearn.log_model(model, "model")

print("✅ Entrenamiento completo. MSE:", mse)