# -*- coding: utf-8 -*-
"""train.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Pu14JlSlkxWMeswz3yDYlDhWo8q8HPh
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/HIPERDAGA/mlflow-colab-demo.git
# %cd mlflow-colab-demo

!pip install -U pip setuptools wheel
!pip install mlflow==2.12.1 cloudpickle

import mlflow
print("MLflow version:", mlflow.__version__)

import os
os.environ["MLFLOW_TRACKING_URI"] = "file:///content/drive/MyDrive/mlruns"

import mlflow
import mlflow.sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.datasets import load_diabetes

# Inicia MLflow
mlflow.set_experiment("demo-linear-regression")

with mlflow.start_run():
    # Carga datos
    data = load_diabetes()
    X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2)

    # Modelo
    model = LinearRegression()
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    # Métricas
    mse = mean_squared_error(y_test, predictions)

    # Registro MLflow
    mlflow.log_param("model_type", "LinearRegression")
    mlflow.log_metric("mse", mse)
    mlflow.sklearn.log_model(model, "model")

print("✅ Entrenamiento completo. MSE:", mse)